server:
  port: 8080
    
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
  datasource:
    url: jdbc:h2:mem:statementdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  cloud:
    stream:
      bindings:
        input:
          destination: queue.orders.events
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: guest
                password: guest
                virtual-host: /
